### PR TITLE
perf_tip_prompter: Add new module to alert the user if the system is …

### PR DESCRIPTION
**Pull request by paolo-github**
…misconfigured for the target test

### CODE REVIEW

**Comment by michaellarabel** [comment]
Thanks, I've merged it and will be making the changes (most of them likely today) as discussed in: https://www.phoronix.com/forums/forum/phoronix/phoronix-test-suite/phoronix-test-suite-developments/963662-bfq_conf_prompter-add-new-module-to-warn-if-the-bfq-i-o-scheduler-is-misconfigured#post963663

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/b15d3f085e5bf238bd936dda3654a07bba1d6713 takes care of reporting the performance tips prior to the overall test execution process rather than prior to running e.g. a disk benchmark

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/4d6b97d39af99df4a4721c8f8d52970f98ee29e6 takes care of styling it nicer making use of PTS CLI features. Also unifies the handling of performance tips and adds in a powersave perf tip as another example.

Also it makes sure not to hang if PTS is running in automated/batch/non-interactive mode.

Current WIP:

screenshot from 2017-07-19 09-18-44

**Comment by michaellarabel** [comment]
Among some other recent comments, I decided to rename perf_tip_prompter to perf_tips so it's shorter and cleaner. In part as in https://github.com/phoronix-test-suite/phoronix-test-suite/commit/3b4699aaaccd25d0fd67d945ff385def361743d2 there is now support for just running `phoronix-test-suite perf_tips.show` for debugging or if just wanting to see all possible performance tips without needing to queue up tests to run.

**Comment by paolo-github** [comment]
> Il giorno 19 lug 2017, alle ore 15:31, Michael Larabel <notifications@github.com> ha scritto:
> 
> Thanks, I've merged it and will be making the changes (most of them likely today) as discussed in: https://www.phoronix.com/forums/forum/phoronix/phoronix-test-suite/phoronix-test-suite-developments/963662-bfq_conf_prompter-add-new-module-to-warn-if-the-bfq-i-o-scheduler-is-misconfigured#post963663
> 

Thank you very much Michael!

I'll proceed now with the next, more complex step: adding a responsiveness test. As usual, any preliminary suggestion is more than welcome.

Paolo

**Pull request merged**
