### PR TITLE
Add support for nproc environment variable

### PR DESCRIPTION
**Pull request by ptzafrir**
This allows to change the cpu count for multiple tests
to test performance under variable number of cpu cores used

### CODE REVIEW

**Comment by michaellarabel** [comment]
Few minor things:

- Would add a check to ensure NPROC is a positive numeric number.
- The NPROC handling would be better in the Phodevi core count function, that way it would also report the overriden NPROC value to the system information table on the results, etc.

Let me know if you have any troubles modifying Phodevi.

**Comment by ptzafrir** [comment]
Is this better?
Without bypassing the cache mechanism the value of core count was not changed when the environment was changed

**Comment by michaellarabel** [comment]
It'd just be cleaner disabling the caching of the core-count value or changing to the standard caching mechanism. If you change in phodevi_cpu.php:


			case 'core-count':
				$property = new phodevi_device_property('cpu_core_count', phodevi::smart_caching);
				break;

from smart_caching to std_caching, then the cache for the core count will only span the lifetime of the program and thus should be fine for the nproc purpose rather than spanning until system reboots. Then you can just keep the nproc check contained to the cpu_core_count function cleanly.

**Comment by ptzafrir** [comment]
using std_caching this way, requires any existing user to disable the cache locally in the configuration file and run PTS once for the change to take effect. (The caching can be turned back on afterwards).
The smart_caching is stored from previous runs and is not modified.

**Comment by michaellarabel** [comment]
@ptzafrir technically true, but for users shouldn't really come into effect unless it's a Git user in the next few days. As soon as I bump the core version, for the next PTS milestone release, the cache should be wiped regardless. So that happens in time for each tagged release or in cases like this I easily bump the core version.

Will go ahead and merge it though see a fix: if (getenv('PTS_NPROC') && is_numeric('PTS_NPROC')) the is_numeric check should be of the getenv(), will fix it on my end.

**Comment by michaellarabel** [comment]
Merged and added: https://github.com/phoronix-test-suite/phoronix-test-suite/commit/2bab1bda45ef9e3760299b99d8bc8e6022f96d06

**Pull request merged**
