### PR TITLE
Support FPS > 500 with libframetime-output

### PR DESCRIPTION
**Pull request by def-**
as noted in https://www.phoronix.com/forums/forum/phoronix/phoronix-test-suite/1220478-how-to-make-test-profile-available-for-others?p=1221512#post1221512

### CODE REVIEW

**Comment by michaellarabel** [comment]
The reason why I added that cut-off in the first place was that all the existing tests up to now are well below 500 FPS. But that cut-off weeded out the loading screen frametimes for the games in PTS up until now. i.e. due to libframetime also reporting the very fast frame times during the initial game load, that was skewing all of the data especially if the user wasn't aware the frametime was being reported for any initial loading screen.

With this patch just always going that route, it would regress the frametime presentation for the existing tests. So perhaps the better solution would be to have it just drop the initial frame times at the very beginning of the stack if the rest of the frametimes are much lower? That would then work nicely for ddnet without messing up the tests on games with normally much lower frame times... Will do some more thinking to see if some other safeguard would work better.

**Comment by def-** [comment]
I guess it's only a matter of time until hardware gets fast enough to go over 500 fps for other games though.

**Comment by michaellarabel** [comment]
Right that's why the ideal situation would be to just drop the initial frames if they are much higher than the rest (i.e. the loading screen time) but will work on thinking how to best handle that logic. Granted, not many test profiles are using the libframetime output anyhow.

**Comment by def-** [comment]
Should I just switch DDNet to another output format if this can't be merged/changed?

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/e9e1ff2833e9754ed7fa89be686c38e5b738ebfd adds 'libframetime-output-no-limit' as using the libframetime-output  but skipping the existing check. So if switching to that -no-limit version should allow the desired behavor while not breaking existing test behavior.

**Comment by def-** [comment]
Thanks, that works for me.

**Comment by def-** [comment]
I have updated https://openbenchmarking.org/test/def/ddnet to support FPS > 500 using your change, could you upload it to pts/ddnet?

Thanks!

**Comment by michaellarabel** [comment]
Thanks @def-, that update should npw be pulled to pts/ddnet-1.1.0.

https://openbenchmarking.org/test/pts/ddnet-1.1.0

**Pull request closed without merging**
