### PR TITLE
Use the actual test identifier, not the index, to get various per-bar colors

### PR DESCRIPTION
**Pull request by MarcinZukowski**

### CODE REVIEW

**Comment by michaellarabel** [comment]
Is there a problem you encountered that led you to this change? $identifier is also used for get_paint_color elsewhere, still checking to see if my original justification for making it that way is still valid.

**Comment by MarcinZukowski** [comment]
Well, I didn't really have a problem per se, but all the bars in my benchmark have the same color, and the code to me suggested that they are supposed to have different colors. So I looked for the culprit, and that seemed to be it.

Maybe something changed in the code at some moment and the identifier that is now 0 used to be an actual run identifiers?

**Comment by michaellarabel** [comment]
Right now it's intended on non-multi-way system comparisons and on non-color-branding for matching the colors of a particular brand if present in the identifier string, it is the same color.

Though if you desire functionality of a random color for each identifier bar, I can see about making it a graph configuration option so users wanting such functionality can opt into it.

**Comment by MarcinZukowski** [comment]
I see.

One other thing I considered was extending GRAPH_HIGHLIGHT functionality, to support not only

    GRAPH_HIGHLIGHT=run_id1,run_id2

but also 

    GRAPH_HIGHLIGHT=run_id1=#FFEEDD,run_id2=#DDEEFF

that might be clearer. Would you support that?

**Comment by michaellarabel** [comment]
I would honor a patch that optionally supported specifying an HTML color code like you mentioned in that patch for GRAPH_HIGHLIGHT, while retaining existing functionality for not specifying a color.

**Pull request closed without merging**
