### PR TITLE
Add configuration option to print all test steps

### PR DESCRIPTION
**Pull request by ptzafrir**
This address issue #95 - FullOutput configuration option is added
If set the output of pre/test/interim/post is dumped to stdout

### CODE REVIEW

**Comment by michaellarabel** [comment]
Hi @ptzafrir the patch appears fine and I have no fundamental issue with merging it. However, I'm just trying to understand your use-case. When in the debug mode (such as by running phoronix-test-suite debug-benchmark) it already prints these outputs. Is there a use-case where you want to see all of this data dumped but not to be in a debug mode? Just trying to understand to ensure this is most effective approach, etc.

Thanks,
MIchael

**Comment by ptzafrir** [comment]
@michaellarabel I'm using PTS not only as a benchmarking system but also as a test system. Sometimes the tests fail, and I would like to have all the information available as to why it happened.
From what I saw, in debug mode the results are not saved as they do in regular mode, so I can't use debug mode all the time.

**Comment by michaellarabel** [comment]
@ptzafrir that's true in debug mode the results aren't saved, didn't think of that. However, your use-case is enough to justify merging it. One item to look at in the future could possibly be extending FullOutput option to say handle dumping to the command-line like currently or just to a file, etc. Just an idea.

**Comment by michaellarabel** [comment]
Merged, thanks. Also added https://github.com/phoronix-test-suite/phoronix-test-suite/commit/bf78f2db131488b03b26570e93eb0d747566270c and https://github.com/phoronix-test-suite/phoronix-test-suite/commit/a3f2256336c2b547ed6451ad870a61f180170c95 that will then add the FullOutput option to user's user-config.xml.

**Comment by ptzafrir** [comment]
Saw it. Thanks!

**Pull request merged**
