### PR TITLE
phodevi: Check more specific ipmitool cpu sensor names first

### PR DESCRIPTION
**Pull request by clbr**
Fixes cpu.temp reporting on a POWER8 server. Otherwise the wrong
sensor was reported.

### CODE REVIEW

**Comment by michaellarabel** [comment]
Perhaps it would be easier just moving this into a for/foreach statement for the different possible ipmi options to check?

**Comment by clbr** [comment]
OK, trying that

**Comment by clbr** [comment]
This ok?

**Comment by michaellarabel** [comment]
Looks good, thanks. Merged.

**Pull request merged**
